server {

    include /etc/nginx/helpers/*.conf;

    listen 8080;

    server_name ~^(.*)$;

    # If a directory doesn't exist...
    if (!-d /sites/$1) {
      # If a client requests a subdomain but the server does not have a folder to serve, redirect back to the main site.
      rewrite . http://www.drupalcamp.es/ redirect;
    }

    # Sets the correct root
    root /sites/$1;
    location / {
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }

}
