server {
    listen 8080;
    server_name drupalcamp.es ~^.*\.drupalcamp\.es$;

    # Default to the most recent edition.
    if ($host ~* "^(www\.)?drupalcamp\.es$") {
        return 301 https://2026.drupalcamp.es/;
    }

    # If a client requests a subdomain but the server does not have a folder to serve, redirect back to the main site.
    if (!-d /sites/$host) {
      return 301 https://www.drupalcamp.es/;
    }

    # Sets the correct root.
    root /sites/$host;
    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 8080;
    server_name drupalday.es ~^.*\.drupalday\.es$;

    # Default to the most recent edition.
    if ($host ~* "^(www\.)?drupalday\.es$") {
      return 301 https://2019.drupalday.es/;
    }

    # If a client requests a subdomain but the server does not have a folder to serve, redirect back to the main site.
    if (!-d /sites/$host) {
      return 301 https://www.drupalday.es/;
    }

    # Sets the correct root.
    root /sites/$host;
    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 8080;
    server_name drupaliberia.eu ~^.*\.drupaliberia\.eu$;

    # Default to the most recent edition.
    if ($host ~* "^(www\.)?drupaliberia\.eu$") {
      return 301 https://2026.drupaliberia.eu/;
    }

    # If a client requests a subdomain but the server does not have a folder to serve, redirect back to the main site.
    if (!-d /sites/$host) {
      return 301 https://www.drupaliberia.eu/;
    }

    # Sets the correct root.
    root /sites/$host;
    location / {
        try_files $uri $uri/ =404;
    }
}
